### ISSUE TITLE
Carousel view cuts the poster

### ISSUE THREAD

**Issue by krnekhelesh** [dslul/cinema-scope#2]
I feel like the carousel view is showing the images in correct aspect ratio but cuts them to do this. The result is a bit weird. Doesn't scope allow the developer to choose which image sizing option to use?

**Comment by mateosalta** [comment]
I've added a pull request that changes the aspect ratio to poster size, which feels more natural on both tv and movies -http://i.stack.imgur.com/ZVAlG.jpg https://github.com/dslul/cinema-scope/pull/7

**Comment by mateosalta** [comment]
maybe wait on pushing that out - it seems the new OTA broke carousel, it was looking really nice like that :/ - and the flim aggregation scope looks like they are able to specify their own layout now, it changed to cubes, even though the design they keep showing is movie poster size... https://developer.ubuntu.com/static/devportal_uploaded/bcfe3a8e-9a03-47c0-afa5-b326eb017708-cms_page_media/7/tablet-features-scopes.jpg
