### ISSUE TITLE
Director unknown

### ISSUE THREAD

**Issue by ic3d** [dslul/cinema-scope#3]
I don't know if it's an issue, but when you tap a movie, most of times the director is "unknown" (see attachments, a pair of examplese). That's quite strange because everything else it's perfect: a lot of intersting infos! :-)

I'm using Ubuntu 14.10 (r14) on mako.

Ciao!
Dario

![cinemascope02](https://cloud.githubusercontent.com/assets/6413651/5843329/3a5c42de-a1ac-11e4-86da-bd9872a6c978.png)
![cinemascope01](https://cloud.githubusercontent.com/assets/6413651/5843330/3a619f22-a1ac-11e4-9647-1cf1a1e1a324.png)

**Comment by dslul** [comment]
Hi Dario, thank you for your feedback!
This is definitely a bug, I fixed it with this commit https://github.com/dslul/cinema-scope/commit/627dbc0f8a211c5b796f28ba67a20ed83a816db1

As soon as i fix some issues with translations i will upload it to the click store :)
Cheers
