### ISSUE TITLE
Some (little) enhancements

### ISSUE THREAD

**Issue by ic3d** [dslul/cinema-scope#4]
I love the Cinema Scope, I use it frequently as i love movies. Using it I saw some little enhancement (suggestion) it could be worth implement in it.

Enhancement #1:

When you search for a movie, sometime you find more than one reasult (e.g. when you search for "Godzilla"). It could be nice to show the list of the movies, and the release year beside the movie title. It could be something like:

[Pic] Godzilla (2014)
[Pic] Godzilla (1998)
[Pic] Godzilla (1954)
. . . . . 

Enhancement #2:

In the "Info" about a movie, you can see "Budget" and "Revenue", but that numbers are pretty illegibles. It could be worth edit that numbers, inserting thousand separators. E.g.: (Godzilla 2014)

Budget: 160000000
Revenue: 524976069

could be better shown as

Budget: 160.000.000
Revenue: 524.976.069

Thanks for your attention! :-)

Dario

**Comment by dslul** [comment]
Hi Dario, thank you again for your feedback, I implemented what you proposed and published a new release on the click store right now :)
If something is not working, please let me know and i'll fix it.

Cheers

**Comment by ic3d** [comment]
Thanks!
